name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "9 6 * * *"

permissions:
  contents: write
  actions: write

jobs:
  resolver:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update && sudo apt-get install -y python3 gh

      - run: pip install -r requirements.txt

      - run: python3 resolver.py

      - run: |
          set -e

          RUNS=$(gh run list --limit 200 --json databaseId -q '.[].databaseId')

          COUNT=0
          for ID in $RUNS; do
            COUNT=$((COUNT+1))
            if [ $COUNT -gt 10 ]; then
              gh run delete "$ID"
            fi
          done
